=== morpel/BattleShipGame3/out/production/BattleShipGame31/Logic/BattleShipGame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="BattleShipGame">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GameType">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="BASIC"/>
                            <xs:enumeration value="ADVANCE"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="boardSize" type="xs:int"/>
                <xs:element name="shipTypes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="shipType" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="category">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="REGULAR"/>
                                                    <xs:enumeration value="L_SHAPE"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:int"/>
                                        <xs:element name="length" type="xs:int"/>
                                        <xs:element name="score" type="xs:int"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mine" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="amount" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="boards">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="board" minOccurs="2" maxOccurs="2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ship" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="shipTypeId" type="xs:string"/>
                                                    <xs:element name="position">
                                                        <xs:complexType>
                                                            <xs:attribute name="x" type="xs:int" use="required" />
                                                            <xs:attribute name="y" type="xs:int" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="direction">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="ROW"/>
                                                                <xs:enumeration value="COLUMN"/>
                                                                <xs:enumeration value="RIGHT_DOWN"/>
                                                                <xs:enumeration value="RIGHT_UP"/>
                                                                <xs:enumeration value="UP_RIGHT"/>
                                                                <xs:enumeration value="DOWN_RIGHT"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== morpel/BattleShipGame3/out/production/BattleShipGame3/resources/battleShip_5_basic_advance.xml
<?xml version="1.0"?>
<BattleShipGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BattleShipGame.xsd">
    <GameType>ADVANCE</GameType>
    <boardSize>10</boardSize>
    <shipTypes>
        <shipType id="shipTypeA">
            <category>L_SHAPE</category>
            <amount>1</amount>
            <length>3</length>
            <score>10</score>
        </shipType>
        <shipType id="shipTypeB">
            <category>REGULAR</category>
            <amount>1</amount>
            <length>2</length>
            <score>5</score>
        </shipType>
    </shipTypes>
    <mine>
        <amount>3</amount>
    </mine>
    <boards>
        <board>
            <ship>
                <shipTypeId>shipTypeA</shipTypeId>
                <position x="2" y="2" />
                <direction>UP_RIGHT</direction>
            </ship>
            <ship>
                <shipTypeId>shipTypeB</shipTypeId>
                <position x="10" y="9" />
                <direction>COLUMN</direction>
            </ship>
        </board>
        <board>
            <ship>
                <shipTypeId>shipTypeA</shipTypeId>
                <position x="1" y="1" />
                <direction>UP_RIGHT</direction>
            </ship>
            <ship>
                <shipTypeId>shipTypeB</shipTypeId>
                <position x="4" y="4" />
                <direction>COLUMN</direction>
            </ship>
        </board>
    </boards>
</BattleShipGame>
